shell fish
shell_integration enabled
title foot

font_family JetBrains Mono Nerd Font
font_size 12.0
confirm_os_window_close 0
scrollback_lines 10000
cursor_shape beam
cursor_beam_thickness 1.5
draw_bold_text_with_bright_colors no
background_opacity 0.78
enable_audio_bell no
window_padding_width 25

# Keep scroll/search workflow close to foot
map page_up scroll_page_up
map page_down scroll_page_down
map ctrl+shift+f show_scrollback
