source = ~/.config/hypr/scheme/current.conf
source = ~/.config/hypr/variables.conf

general {
    hide_cursor = true
    ignore_empty_input = true
    immediate_render = true
    fail_timeout = 1500
}

auth {
    pam:enabled = true
}

animations {
    enabled = true
}

background {
    monitor =
    path = ~/.local/state/caelestia/wallpaper/current
    color = rgba($baseff)
    blur_passes = 2
    blur_size = 6
    vibrancy = 0.1
    brightness = 0.8
    contrast = 0.92
    noise = 0.01
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = rgba($onSurfaceff)
    font_size = 72
    position = 0, 128
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%A, %d %B %Y"
    color = rgba($onSurfaceVariantdd)
    font_size = 18
    position = 0, 188
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgba($primaryee)
    font_size = 24
    position = 0, -148
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 320, 58
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.18
    dots_center = true
    outer_color = rgba($primarycc)
    inner_color = rgba($surfaceContainerHighd9)
    font_color = rgba($onSurfaceff)
    fade_on_empty = false
    hide_input = false
    rounding = 18
    check_color = rgba($primaryff)
    fail_color = rgba($errordd)
    capslock_color = rgba($yellowdd)
    position = 0, -58
    halign = center
    valign = center
}
